defaults: &defaults
  pool: 55
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  username: root
  password: <%= ENV['MYSQL_USER_PASSWORD'].to_s rescue '' %>

development:
  <<: *defaults
  database: geonames

test:
  <<: *defaults
  database: geonames_test
